name: build and deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SOURCE_DIR: source-dir
      DEPLOY_DIR: deploy-dir
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: $ {{ SOURCE_DIR }}

      - name: Checkout tools repo
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: deploy
        
      - name: "echoes"
        run: |
          pwd
          ls 
          echo ------------------------------
          ls $ {{ SOURCE_DIR }}
          echo -------------------------------
          ls deploy


      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - uses: actions/cache@v1 # this allows for re-using node_modules caching, making builds a bit faster.
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setup angular
        run: |
          cd $ {{ SOURCE_DIR }}
          npm install
          npm install -g @angular/cli > /dev/null

      - name: Build angular project
        run: |
          cd $ {{ SOURCE_DIR }}
          ls
          ng build --prod --base-href "https://juaamol.github.io/portfolio-website/"

      - name: Prepare deploy branch
        run: |
          rm -r deploy/*
          cp $ {{ SOURCE_DIR }}/dist/portfolio-website deploy
          ls deploy

      - name: Deploy to github pages
        run: |
          cd deploy
          git status
          
        env:
          CI: true
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
